// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uoyupwiyymkpviauisfa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVveXVwd2l5eW1rcHZpYXVpc2ZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzODQwMTAsImV4cCI6MjA3MTk2MDAxMH0.ur9bH5RrHdUAQpMCtS7RBvhntszkMIIpyPPkmF4d0Tc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});